logging:
  level:
    root: info
    com.camelot.kuka: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.69.18:3306/kuka_manage_backend?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 8
    max-idle: 8
    max-active: 20
    minEvictableIdleTimeMillis: 300000
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters:  stat,wall,log4j2
    connectionPropertie:  druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  mail:
    default-encoding: UTF-8
    host: smtp.qq.com
    username: 136122030@qq.com
    password: dnhyiyhzcpvhbggh
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
      host: 123.57.69.18
      port: 6379
      password:
      timeout: 10s
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
          max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
mybatis:
  type-aliases-package: com.camelot.kuka.backend.model,com.camelot.kuka.model.mail
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true
    type-handlers-package: com.camelot.kuka.common.mybatis.handler

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/api/api-o/user-me
      prefer-token-info: false